export interface Country {
  code: string;
  name: string;
  currency: string;
  currencySymbol: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", currency: "AFN", currencySymbol: "؋", flag: "🇦🇫" },
  { code: "AL", name: "Albania", currency: "ALL", currencySymbol: "L", flag: "🇦🇱" },
  { code: "DZ", name: "Algeria", currency: "DZD", currencySymbol: "د.ج", flag: "🇩🇿" },
  { code: "AD", name: "Andorra", currency: "EUR", currencySymbol: "€", flag: "🇦🇩" },
  { code: "AO", name: "Angola", currency: "AOA", currencySymbol: "Kz", flag: "🇦🇴" },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD", currencySymbol: "$", flag: "🇦🇬" },
  { code: "AR", name: "Argentina", currency: "ARS", currencySymbol: "$", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", currency: "AMD", currencySymbol: "֏", flag: "🇦🇲" },
  { code: "AU", name: "Australia", currency: "AUD", currencySymbol: "A$", flag: "🇦🇺" },
  { code: "AT", name: "Austria", currency: "EUR", currencySymbol: "€", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", currencySymbol: "₼", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", currency: "BSD", currencySymbol: "$", flag: "🇧🇸" },
  { code: "BH", name: "Bahrain", currency: "BHD", currencySymbol: ".د.ب", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", currency: "BDT", currencySymbol: "৳", flag: "🇧🇩" },
  { code: "BB", name: "Barbados", currency: "BBD", currencySymbol: "$", flag: "🇧🇧" },
  { code: "BY", name: "Belarus", currency: "BYN", currencySymbol: "Br", flag: "🇧🇾" },
  { code: "BE", name: "Belgium", currency: "EUR", currencySymbol: "€", flag: "🇧🇪" },
  { code: "BZ", name: "Belize", currency: "BZD", currencySymbol: "$", flag: "🇧🇿" },
  { code: "BJ", name: "Benin", currency: "XOF", currencySymbol: "CFA", flag: "🇧🇯" },
  { code: "BT", name: "Bhutan", currency: "BTN", currencySymbol: "Nu.", flag: "🇧🇹" },
  { code: "BO", name: "Bolivia", currency: "BOB", currencySymbol: "Bs.", flag: "🇧🇴" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", currencySymbol: "KM", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", currency: "BWP", currencySymbol: "P", flag: "🇧🇼" },
  { code: "BR", name: "Brazil", currency: "BRL", currencySymbol: "R$", flag: "🇧🇷" },
  { code: "BN", name: "Brunei", currency: "BND", currencySymbol: "$", flag: "🇧🇳" },
  { code: "BG", name: "Bulgaria", currency: "BGN", currencySymbol: "лв", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", currencySymbol: "CFA", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", currency: "BIF", currencySymbol: "FBu", flag: "🇧🇮" },
  { code: "KH", name: "Cambodia", currency: "KHR", currencySymbol: "៛", flag: "🇰🇭" },
  { code: "CM", name: "Cameroon", currency: "XAF", currencySymbol: "FCFA", flag: "🇨🇲" },
  { code: "CA", name: "Canada", currency: "CAD", currencySymbol: "C$", flag: "🇨🇦" },
  { code: "CV", name: "Cape Verde", currency: "CVE", currencySymbol: "$", flag: "🇨🇻" },
  { code: "CF", name: "Central African Republic", currency: "XAF", currencySymbol: "FCFA", flag: "🇨🇫" },
  { code: "TD", name: "Chad", currency: "XAF", currencySymbol: "FCFA", flag: "🇹🇩" },
  { code: "CL", name: "Chile", currency: "CLP", currencySymbol: "$", flag: "🇨🇱" },
  { code: "CN", name: "China", currency: "CNY", currencySymbol: "¥", flag: "🇨🇳" },
  { code: "CO", name: "Colombia", currency: "COP", currencySymbol: "$", flag: "🇨🇴" },
  { code: "KM", name: "Comoros", currency: "KMF", currencySymbol: "CF", flag: "🇰🇲" },
  { code: "CG", name: "Congo", currency: "XAF", currencySymbol: "FCFA", flag: "🇨🇬" },
  { code: "CD", name: "Congo (DRC)", currency: "CDF", currencySymbol: "FC", flag: "🇨🇩" },
  { code: "CR", name: "Costa Rica", currency: "CRC", currencySymbol: "₡", flag: "🇨🇷" },
  { code: "HR", name: "Croatia", currency: "EUR", currencySymbol: "€", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", currency: "CUP", currencySymbol: "$", flag: "🇨🇺" },
  { code: "CY", name: "Cyprus", currency: "EUR", currencySymbol: "€", flag: "🇨🇾" },
  { code: "CZ", name: "Czech Republic", currency: "CZK", currencySymbol: "Kč", flag: "🇨🇿" },
  { code: "DK", name: "Denmark", currency: "DKK", currencySymbol: "kr", flag: "🇩🇰" },
  { code: "DJ", name: "Djibouti", currency: "DJF", currencySymbol: "Fdj", flag: "🇩🇯" },
  { code: "DM", name: "Dominica", currency: "XCD", currencySymbol: "$", flag: "🇩🇲" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", currencySymbol: "RD$", flag: "🇩🇴" },
  { code: "EC", name: "Ecuador", currency: "USD", currencySymbol: "$", flag: "🇪🇨" },
  { code: "EG", name: "Egypt", currency: "EGP", currencySymbol: "E£", flag: "🇪🇬" },
  { code: "SV", name: "El Salvador", currency: "USD", currencySymbol: "$", flag: "🇸🇻" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", currencySymbol: "FCFA", flag: "🇬🇶" },
  { code: "ER", name: "Eritrea", currency: "ERN", currencySymbol: "Nfk", flag: "🇪🇷" },
  { code: "EE", name: "Estonia", currency: "EUR", currencySymbol: "€", flag: "🇪🇪" },
  { code: "SZ", name: "Eswatini", currency: "SZL", currencySymbol: "E", flag: "🇸🇿" },
  { code: "ET", name: "Ethiopia", currency: "ETB", currencySymbol: "Br", flag: "🇪🇹" },
  { code: "FJ", name: "Fiji", currency: "FJD", currencySymbol: "$", flag: "🇫🇯" },
  { code: "FI", name: "Finland", currency: "EUR", currencySymbol: "€", flag: "🇫🇮" },
  { code: "FR", name: "France", currency: "EUR", currencySymbol: "€", flag: "🇫🇷" },
  { code: "GA", name: "Gabon", currency: "XAF", currencySymbol: "FCFA", flag: "🇬🇦" },
  { code: "GM", name: "Gambia", currency: "GMD", currencySymbol: "D", flag: "🇬🇲" },
  { code: "GE", name: "Georgia", currency: "GEL", currencySymbol: "₾", flag: "🇬🇪" },
  { code: "DE", name: "Germany", currency: "EUR", currencySymbol: "€", flag: "🇩🇪" },
  { code: "GH", name: "Ghana", currency: "GHS", currencySymbol: "₵", flag: "🇬🇭" },
  { code: "GR", name: "Greece", currency: "EUR", currencySymbol: "€", flag: "🇬🇷" },
  { code: "GD", name: "Grenada", currency: "XCD", currencySymbol: "$", flag: "🇬🇩" },
  { code: "GT", name: "Guatemala", currency: "GTQ", currencySymbol: "Q", flag: "🇬🇹" },
  { code: "GN", name: "Guinea", currency: "GNF", currencySymbol: "FG", flag: "🇬🇳" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", currencySymbol: "CFA", flag: "🇬🇼" },
  { code: "GY", name: "Guyana", currency: "GYD", currencySymbol: "$", flag: "🇬🇾" },
  { code: "HT", name: "Haiti", currency: "HTG", currencySymbol: "G", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", currency: "HNL", currencySymbol: "L", flag: "🇭🇳" },
  { code: "HU", name: "Hungary", currency: "HUF", currencySymbol: "Ft", flag: "🇭🇺" },
  { code: "IS", name: "Iceland", currency: "ISK", currencySymbol: "kr", flag: "🇮🇸" },
  { code: "IN", name: "India", currency: "INR", currencySymbol: "₹", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", currency: "IDR", currencySymbol: "Rp", flag: "🇮🇩" },
  { code: "IR", name: "Iran", currency: "IRR", currencySymbol: "﷼", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", currency: "IQD", currencySymbol: "ع.د", flag: "🇮🇶" },
  { code: "IE", name: "Ireland", currency: "EUR", currencySymbol: "€", flag: "🇮🇪" },
  { code: "IL", name: "Israel", currency: "ILS", currencySymbol: "₪", flag: "🇮🇱" },
  { code: "IT", name: "Italy", currency: "EUR", currencySymbol: "€", flag: "🇮🇹" },
  { code: "CI", name: "Ivory Coast", currency: "XOF", currencySymbol: "CFA", flag: "🇨🇮" },
  { code: "JM", name: "Jamaica", currency: "JMD", currencySymbol: "J$", flag: "🇯🇲" },
  { code: "JP", name: "Japan", currency: "JPY", currencySymbol: "¥", flag: "🇯🇵" },
  { code: "JO", name: "Jordan", currency: "JOD", currencySymbol: "د.ا", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", currencySymbol: "₸", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", currency: "KES", currencySymbol: "KSh", flag: "🇰🇪" },
  { code: "KI", name: "Kiribati", currency: "AUD", currencySymbol: "$", flag: "🇰🇮" },
  { code: "KW", name: "Kuwait", currency: "KWD", currencySymbol: "د.ك", flag: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", currencySymbol: "лв", flag: "🇰🇬" },
  { code: "LA", name: "Laos", currency: "LAK", currencySymbol: "₭", flag: "🇱🇦" },
  { code: "LV", name: "Latvia", currency: "EUR", currencySymbol: "€", flag: "🇱🇻" },
  { code: "LB", name: "Lebanon", currency: "LBP", currencySymbol: "ل.ل", flag: "🇱🇧" },
  { code: "LS", name: "Lesotho", currency: "LSL", currencySymbol: "L", flag: "🇱🇸" },
  { code: "LR", name: "Liberia", currency: "LRD", currencySymbol: "$", flag: "🇱🇷" },
  { code: "LY", name: "Libya", currency: "LYD", currencySymbol: "ل.د", flag: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", currencySymbol: "CHF", flag: "🇱🇮" },
  { code: "LT", name: "Lithuania", currency: "EUR", currencySymbol: "€", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", currency: "EUR", currencySymbol: "€", flag: "🇱🇺" },
  { code: "MG", name: "Madagascar", currency: "MGA", currencySymbol: "Ar", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", currency: "MWK", currencySymbol: "MK", flag: "🇲🇼" },
  { code: "MY", name: "Malaysia", currency: "MYR", currencySymbol: "RM", flag: "🇲🇾" },
  { code: "MV", name: "Maldives", currency: "MVR", currencySymbol: "Rf", flag: "🇲🇻" },
  { code: "ML", name: "Mali", currency: "XOF", currencySymbol: "CFA", flag: "🇲🇱" },
  { code: "MT", name: "Malta", currency: "EUR", currencySymbol: "€", flag: "🇲🇹" },
  { code: "MH", name: "Marshall Islands", currency: "USD", currencySymbol: "$", flag: "🇲🇭" },
  { code: "MR", name: "Mauritania", currency: "MRU", currencySymbol: "UM", flag: "🇲🇷" },
  { code: "MU", name: "Mauritius", currency: "MUR", currencySymbol: "₨", flag: "🇲🇺" },
  { code: "MX", name: "Mexico", currency: "MXN", currencySymbol: "$", flag: "🇲🇽" },
  { code: "FM", name: "Micronesia", currency: "USD", currencySymbol: "$", flag: "🇫🇲" },
  { code: "MD", name: "Moldova", currency: "MDL", currencySymbol: "L", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", currency: "EUR", currencySymbol: "€", flag: "🇲🇨" },
  { code: "MN", name: "Mongolia", currency: "MNT", currencySymbol: "₮", flag: "🇲🇳" },
  { code: "ME", name: "Montenegro", currency: "EUR", currencySymbol: "€", flag: "🇲🇪" },
  { code: "MA", name: "Morocco", currency: "MAD", currencySymbol: "د.م.", flag: "🇲🇦" },
  { code: "MZ", name: "Mozambique", currency: "MZN", currencySymbol: "MT", flag: "🇲🇿" },
  { code: "MM", name: "Myanmar", currency: "MMK", currencySymbol: "K", flag: "🇲🇲" },
  { code: "NA", name: "Namibia", currency: "NAD", currencySymbol: "$", flag: "🇳🇦" },
  { code: "NR", name: "Nauru", currency: "AUD", currencySymbol: "$", flag: "🇳🇷" },
  { code: "NP", name: "Nepal", currency: "NPR", currencySymbol: "रू", flag: "🇳🇵" },
  { code: "NL", name: "Netherlands", currency: "EUR", currencySymbol: "€", flag: "🇳🇱" },
  { code: "NZ", name: "New Zealand", currency: "NZD", currencySymbol: "NZ$", flag: "🇳🇿" },
  { code: "NI", name: "Nicaragua", currency: "NIO", currencySymbol: "C$", flag: "🇳🇮" },
  { code: "NE", name: "Niger", currency: "XOF", currencySymbol: "CFA", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", currency: "NGN", currencySymbol: "₦", flag: "🇳🇬" },
  { code: "KP", name: "North Korea", currency: "KPW", currencySymbol: "₩", flag: "🇰🇵" },
  { code: "MK", name: "North Macedonia", currency: "MKD", currencySymbol: "ден", flag: "🇲🇰" },
  { code: "NO", name: "Norway", currency: "NOK", currencySymbol: "kr", flag: "🇳🇴" },
  { code: "OM", name: "Oman", currency: "OMR", currencySymbol: "ر.ع.", flag: "🇴🇲" },
  { code: "PK", name: "Pakistan", currency: "PKR", currencySymbol: "₨", flag: "🇵🇰" },
  { code: "PW", name: "Palau", currency: "USD", currencySymbol: "$", flag: "🇵🇼" },
  { code: "PS", name: "Palestine", currency: "ILS", currencySymbol: "₪", flag: "🇵🇸" },
  { code: "PA", name: "Panama", currency: "PAB", currencySymbol: "B/.", flag: "🇵🇦" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", currencySymbol: "K", flag: "🇵🇬" },
  { code: "PY", name: "Paraguay", currency: "PYG", currencySymbol: "₲", flag: "🇵🇾" },
  { code: "PE", name: "Peru", currency: "PEN", currencySymbol: "S/", flag: "🇵🇪" },
  { code: "PH", name: "Philippines", currency: "PHP", currencySymbol: "₱", flag: "🇵🇭" },
  { code: "PL", name: "Poland", currency: "PLN", currencySymbol: "zł", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", currency: "EUR", currencySymbol: "€", flag: "🇵🇹" },
  { code: "QA", name: "Qatar", currency: "QAR", currencySymbol: "ر.ق", flag: "🇶🇦" },
  { code: "RO", name: "Romania", currency: "RON", currencySymbol: "lei", flag: "🇷🇴" },
  { code: "RU", name: "Russia", currency: "RUB", currencySymbol: "₽", flag: "🇷🇺" },
  { code: "RW", name: "Rwanda", currency: "RWF", currencySymbol: "FRw", flag: "🇷🇼" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", currencySymbol: "$", flag: "🇰🇳" },
  { code: "LC", name: "Saint Lucia", currency: "XCD", currencySymbol: "$", flag: "🇱🇨" },
  { code: "VC", name: "Saint Vincent", currency: "XCD", currencySymbol: "$", flag: "🇻🇨" },
  { code: "WS", name: "Samoa", currency: "WST", currencySymbol: "T", flag: "🇼🇸" },
  { code: "SM", name: "San Marino", currency: "EUR", currencySymbol: "€", flag: "🇸🇲" },
  { code: "ST", name: "Sao Tome and Principe", currency: "STN", currencySymbol: "Db", flag: "🇸🇹" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", currencySymbol: "ر.س", flag: "🇸🇦" },
  { code: "SN", name: "Senegal", currency: "XOF", currencySymbol: "CFA", flag: "🇸🇳" },
  { code: "RS", name: "Serbia", currency: "RSD", currencySymbol: "дин.", flag: "🇷🇸" },
  { code: "SC", name: "Seychelles", currency: "SCR", currencySymbol: "₨", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", currency: "SLL", currencySymbol: "Le", flag: "🇸🇱" },
  { code: "SG", name: "Singapore", currency: "SGD", currencySymbol: "S$", flag: "🇸🇬" },
  { code: "SK", name: "Slovakia", currency: "EUR", currencySymbol: "€", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", currency: "EUR", currencySymbol: "€", flag: "🇸🇮" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", currencySymbol: "$", flag: "🇸🇧" },
  { code: "SO", name: "Somalia", currency: "SOS", currencySymbol: "S", flag: "🇸🇴" },
  { code: "ZA", name: "South Africa", currency: "ZAR", currencySymbol: "R", flag: "🇿🇦" },
  { code: "KR", name: "South Korea", currency: "KRW", currencySymbol: "₩", flag: "🇰🇷" },
  { code: "SS", name: "South Sudan", currency: "SSP", currencySymbol: "£", flag: "🇸🇸" },
  { code: "ES", name: "Spain", currency: "EUR", currencySymbol: "€", flag: "🇪🇸" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", currencySymbol: "₨", flag: "🇱🇰" },
  { code: "SD", name: "Sudan", currency: "SDG", currencySymbol: "ج.س.", flag: "🇸🇩" },
  { code: "SR", name: "Suriname", currency: "SRD", currencySymbol: "$", flag: "🇸🇷" },
  { code: "SE", name: "Sweden", currency: "SEK", currencySymbol: "kr", flag: "🇸🇪" },
  { code: "CH", name: "Switzerland", currency: "CHF", currencySymbol: "CHF", flag: "🇨🇭" },
  { code: "SY", name: "Syria", currency: "SYP", currencySymbol: "£", flag: "🇸🇾" },
  { code: "TW", name: "Taiwan", currency: "TWD", currencySymbol: "NT$", flag: "🇹🇼" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", currencySymbol: "SM", flag: "🇹🇯" },
  { code: "TZ", name: "Tanzania", currency: "TZS", currencySymbol: "TSh", flag: "🇹🇿" },
  { code: "TH", name: "Thailand", currency: "THB", currencySymbol: "฿", flag: "🇹🇭" },
  { code: "TL", name: "Timor-Leste", currency: "USD", currencySymbol: "$", flag: "🇹🇱" },
  { code: "TG", name: "Togo", currency: "XOF", currencySymbol: "CFA", flag: "🇹🇬" },
  { code: "TO", name: "Tonga", currency: "TOP", currencySymbol: "T$", flag: "🇹🇴" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", currencySymbol: "TT$", flag: "🇹🇹" },
  { code: "TN", name: "Tunisia", currency: "TND", currencySymbol: "د.ت", flag: "🇹🇳" },
  { code: "TR", name: "Turkey", currency: "TRY", currencySymbol: "₺", flag: "🇹🇷" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", currencySymbol: "m", flag: "🇹🇲" },
  { code: "TV", name: "Tuvalu", currency: "AUD", currencySymbol: "$", flag: "🇹🇻" },
  { code: "UG", name: "Uganda", currency: "UGX", currencySymbol: "USh", flag: "🇺🇬" },
  { code: "UA", name: "Ukraine", currency: "UAH", currencySymbol: "₴", flag: "🇺🇦" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", currencySymbol: "د.إ", flag: "🇦🇪" },
  { code: "GB", name: "United Kingdom", currency: "GBP", currencySymbol: "£", flag: "🇬🇧" },
  { code: "US", name: "United States", currency: "USD", currencySymbol: "$", flag: "🇺🇸" },
  { code: "UY", name: "Uruguay", currency: "UYU", currencySymbol: "$U", flag: "🇺🇾" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", currencySymbol: "лв", flag: "🇺🇿" },
  { code: "VU", name: "Vanuatu", currency: "VUV", currencySymbol: "VT", flag: "🇻🇺" },
  { code: "VA", name: "Vatican City", currency: "EUR", currencySymbol: "€", flag: "🇻🇦" },
  { code: "VE", name: "Venezuela", currency: "VES", currencySymbol: "Bs.", flag: "🇻🇪" },
  { code: "VN", name: "Vietnam", currency: "VND", currencySymbol: "₫", flag: "🇻🇳" },
  { code: "YE", name: "Yemen", currency: "YER", currencySymbol: "﷼", flag: "🇾🇪" },
  { code: "ZM", name: "Zambia", currency: "ZMW", currencySymbol: "ZK", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", currencySymbol: "$", flag: "🇿🇼" },
];

export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find(c => c.code === code);
};

export const getCountryCurrency = (code: string): { currency: string; symbol: string } => {
  const country = getCountryByCode(code);
  return {
    currency: country?.currency || "INR",
    symbol: country?.currencySymbol || "₹"
  };
};

export const formatCurrency = (amount: number | string, countryCode: string): string => {
  const { symbol } = getCountryCurrency(countryCode);
  const numAmount = typeof amount === "string" ? parseFloat(amount) : amount;
  return `${symbol}${numAmount.toLocaleString()}`;
};
